### ISSUE TITLE
pub.dev: package is discontinued

### ISSUE THREAD

**Issue by proninyaroslav** [mashnoon33/circular_check_box#18]
Package is no longer supported?

**Comment by Nico04** [comment]
It seems that with new shape property this plugin isn't needed anymore, we should be able to use native Flutter CheckBox widget (not tested yet).
https://api.flutter.dev/flutter/material/CheckboxThemeData/shape.html
https://github.com/flutter/flutter/pull/70171

**Comment by proninyaroslav** [comment]
@Nico04 
Yes, https://github.com/mashnoon33/circular_check_box/issues/19#issuecomment-845188308
