### ISSUE TITLE
After migration on flutter 1.17 application wont build

### ISSUE THREAD

**Issue by pinball83** [mashnoon33/circular_check_box#5]
> Compiler message:
../flutter-sdk/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:168:13: Error: Expected 0 type arguments.
  Map<Type, Action<Intent>> _actionMap;
            ^
../flutter-sdk/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:178:23: Error: Type 'ActivateIntent' not found.
  void _actionHandler(ActivateIntent intent){
                      ^^^^^^^^^^^^^^
../flutter-sdk/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:173:25: Error: Expected 0 type arguments.
    _actionMap = <Type, Action<Intent>>{
                        ^^^^^^
../flutter-sdk/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:174:38: Error: 'ActivateIntent' isn't a type.
      ActivateIntent: CallbackAction<ActivateIntent>(onInvoke: _actionHandler),
                                     ^^^^^^^^^^^^^^
../flutter-sdk/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:174:53: Error: Too few positional arguments: 1 required, 0 given.
      ActivateIntent: CallbackAction<ActivateIntent>(onInvoke: _actionHandler),
                                                    ^
../flutter-sdk/packages/flutter/lib/src/widgets/actions.dart:128:9: Context: Found this candidate, but the arguments don't match.
  const CallbackAction(LocalKey intentKey, {@required this.onInvoke})
        ^^^^^^^^^^^^^^
../flutter-sdk/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:174:7: Error: The getter 'ActivateIntent' isn't defined for the class '_CircularCheckBoxState'.
 - '_CircularCheckBoxState' is from 'package:circular_check_box/circular_check_box.dart' ('../flutter-sdk/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ActivateIntent'.
      ActivateIntent: CallbackAction<ActivateIntent>(onInvoke: _actionHandler),
      ^^^^^^^^^^^^^^
../flutter-sdk/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:173:40: Error: A value of type 'Map<Type, Action>' can't be assigned to a variable of type 'Map<Type, invalid-type>'.
 - 'Map' is from 'dart:core'.
 - 'Type' is from 'dart:core'.
 - 'Action' is from 'package:flutter/src/widgets/actions.dart' ('../flutter-sdk/packages/flutter/lib/src/widgets/actions.dart').
    _actionMap = <Type, Action<Intent>>{
                                       ^
../flutter-sdk/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:178:23: Error: 'ActivateIntent' isn't a type.
  void _actionHandler(ActivateIntent intent){
                      ^^^^^^^^^^^^^^
../flutter-sdk/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:226:16: Error: The argument type 'Map<Type, invalid-type>' can't be assigned to the parameter type 'Map<LocalKey, Action Function()>'.
 - 'Map' is from 'dart:core'.
 - 'Type' is from 'dart:core'.
 - 'LocalKey' is from 'package:flutter/src/foundation/key.dart' ('../flutter-sdk/packages/flutter/lib/src/foundation/key.dart').
 - 'Action' is from 'package:flutter/src/widgets/actions.dart' ('../flutter-sdk/packages/flutter/lib/src/widgets/actions.dart').
      actions: _actionMap,
               ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null

**Comment by abin-saju** [comment]
Forcing v1.0.1 resolves the issue for now

**Comment by MartinSchultz** [comment]
Thanks, fixing on 1.0.1 solved it for me too.

**Comment by kylermintah** [comment]
Thanks! 1.0.1 fixed for me too

**Comment by jpmehedi** [comment]
Launching lib\main.dart on roarV95 in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:168:13: Error: Expected 0 type arguments.
  Map<Type, Action<Intent>> _actionMap;
            ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:178:23: Error: Type 'ActivateIntent' not found.
  void _actionHandler(ActivateIntent intent){
                      ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:173:25: Error: Expected 0 type arguments.
    _actionMap = <Type, Action<Intent>>{
                        ^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:174:38: Error: 'ActivateIntent' isn't a type.
      ActivateIntent: CallbackAction<ActivateIntent>(onInvoke: _actionHandler),
                                     ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:174:53: Error: Too few positional arguments: 1 required, 0 given.
      ActivateIntent: CallbackAction<ActivateIntent>(onInvoke: _actionHandler),
                                                    ^
/C:/src/flutter/packages/flutter/lib/src/widgets/actions.dart:128:9: Context: Found this candidate, but the arguments don't match.
  const CallbackAction(LocalKey intentKey, {@required this.onInvoke})
        ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:174:7: Error: The getter 'ActivateIntent' isn't defined for the class '_CircularCheckBoxState'.
 - '_CircularCheckBoxState' is from 'package:circular_check_box/circular_check_box.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ActivateIntent'.
      ActivateIntent: CallbackAction<ActivateIntent>(onInvoke: _actionHandler),
      ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:173:40: Error: A value of type 'Map<Type, Action>' can't be assigned to a variable of type 'Map<Type, invalid-type>'.
 - 'Map' is from 'dart:core'.
 - 'Type' is from 'dart:core'.
 - 'Action' is from 'package:flutter/src/widgets/actions.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/actions.dart').
    _actionMap = <Type, Action<Intent>>{
                                       ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:178:23: Error: 'ActivateIntent' isn't a type.
  void _actionHandler(ActivateIntent intent){
                      ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:226:16: Error: The argument type 'Map<Type, invalid-type>' can't be assigned to the parameter type 'Map<LocalKey, Action Function()>'.
 - 'Map' is from 'dart:core'.
 - 'Type' is from 'dart:core'.
 - 'LocalKey' is from 'package:flutter/src/foundation/key.dart' ('/C:/src/flutter/packages/flutter/lib/src/foundation/key.dart').
 - 'Action' is from 'package:flutter/src/widgets/actions.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/actions.dart').
      actions: _actionMap,
               ^

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:168:13: Error: Expected 0 type arguments.
  Map<Type, Action<Intent>> _actionMap;
            ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:178:23: Error: Type 'ActivateIntent' not found.
  void _actionHandler(ActivateIntent intent){
                      ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:173:25: Error: Expected 0 type arguments.
    _actionMap = <Type, Action<Intent>>{
                        ^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:174:38: Error: 'ActivateIntent' isn't a type.
      ActivateIntent: CallbackAction<ActivateIntent>(onInvoke: _actionHandler),
                                     ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:174:53: Error: Too few positional arguments: 1 required, 0 given.
      ActivateIntent: CallbackAction<ActivateIntent>(onInvoke: _actionHandler),
                                                    ^
/C:/src/flutter/packages/flutter/lib/src/widgets/actions.dart:128:9: Context: Found this candidate, but the arguments don't match.
  const CallbackAction(LocalKey intentKey, {@required this.onInvoke})
        ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:174:7: Error: The getter 'ActivateIntent' isn't defined for the class '_CircularCheckBoxState'.
 - '_CircularCheckBoxState' is from 'package:circular_check_box/circular_check_box.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ActivateIntent'.
      ActivateIntent: CallbackAction<ActivateIntent>(onInvoke: _actionHandler),
      ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:173:40: Error: A value of type 'Map<Type, Action>' can't be assigned to a variable of type 'Map<Type, invalid-type>'.
 - 'Map' is from 'dart:core'.
 - 'Type' is from 'dart:core'.
 - 'Action' is from 'package:flutter/src/widgets/actions.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/actions.dart').
    _actionMap = <Type, Action<Intent>>{
                                       ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:178:23: Error: 'ActivateIntent' isn't a type.
  void _actionHandler(ActivateIntent intent){
                      ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.2/lib/circular_check_box.dart:226:16: Error: The argument type 'Map<Type, invalid-type>' can't be assigned to the parameter type 'Map<LocalKey, Action Function()>'.
 - 'Map' is from 'dart:core'.
 - 'Type' is from 'dart:core'.
 - 'LocalKey' is from 'package:flutter/src/foundation/key.dart' ('/C:/src/flutter/packages/flutter/lib/src/foundation/key.dart').
 - 'Action' is from 'package:flutter/src/widgets/actions.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/actions.dart').
      actions: _actionMap,
               ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Exception: Gradle task assembleDebug failed with exit code 1
